apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: capstone-dev
  labels:
    app: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: dakshsawhneyy/capstone_frontend:0ee1d2af124100758adfb250bf52b842d21be0f3
          ports:
            - containerPort: 80

---
# LoadBalancer — exposes frontend to the outside world (browser access)
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: capstone-dev
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
