name: CI Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and Push Frontend Image
      #   working-directory: app/frontend
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/capstone_frontend:latest .
      #     docker push ${{ secrets.DOCKER_USERNAME }}/capstone_frontend:latest
      
      # - name: Build and Push Backend Image
      #   working-directory: app/backend
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/capstone_backend:latest .
      #     docker push ${{ secrets.DOCKER_USERNAME }}/capstone_backend:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform-version: "1.18.0"
          terraform_wrapper: false

      - name: Configure AWS Creadentials
        uses: aws-actions/configure-aws-credentials@v6.2.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: infra/terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: infra/terraform
        run: terraform apply --auto-approve

      # - name: Get EC2 IP
      #   id: ec2
      #   working-directory: infra/terraform
      #   run: |
      #     echo "ip=$(terraform output -raw instance_public_ip)" >> "$GITHUB_OUTPUT"

      # - name: Debug EC2 IP
      #   run: |
      #     echo "IP is: ${{ steps.ec2.outputs.ip }}"

      #   # Install Ansible
      # - name: Install Ansible
      #   run: |
      #       sudo apt update
      #       sudo apt install software-properties-common
      #       sudo add-apt-repository --yes --update ppa:ansible/ansible
      #       sudo apt install ansible


      # - name: Configure SSH Key
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/general.pem
      #     chmod 400 ~/.ssh/general.pem

      # - name: Generate Inventory
      #   run: |
      #     cat > infra/ansible/inventory.ini <<EOF
      #     [servers]
      #     ${{ steps.ec2.outputs.ip }}

      #     [servers:vars]
      #     ansible_user=ubuntu
      #     ansible_ssh_private_key_file=~/.ssh/general.pem
      #     ansible_python_interpreter=/usr/bin/python3
      #     EOF

      # - name: Print Inventory
      #   run: |
      #     cat infra/ansible/inventory.ini

      # - name: Add EC2 host key
      #   run: |
      #     ssh-keyscan -H ${{ steps.ec2.outputs.ip }} >> ~/.ssh/known_hosts

      # - name: Run Ansible Playbook
      #   working-directory: infra/ansible
      #   # env:
      #   #   ANSIBLE_HOST_KEY_CHECKING: False
      #   run: |
      #     ansible-playbook -i inventory.ini -v final-playbook.yml

      - name: Install Kubectl 
        run: sudo snap install kubectl --classic

      - name: Configure Kubeconfig for EKS
        run: aws eks update-kubeconfig --name capstone-eks --region ap-south-1